//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExploreLocalEntities1 : DbContext
    {
        public ExploreLocalEntities1()
            : base("name=ExploreLocalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Announcement> Tbl_Announcement { get; set; }
        public virtual DbSet<Tbl_Bookings> Tbl_Bookings { get; set; }
        public virtual DbSet<Tbl_Comments> Tbl_Comments { get; set; }
        public virtual DbSet<Tbl_Destination> Tbl_Destination { get; set; }
        public virtual DbSet<Tbl_Expert> Tbl_Expert { get; set; }
        public virtual DbSet<Tbl_Replies> Tbl_Replies { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_Venue> Tbl_Venue { get; set; }
    }
}
