//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Announcement
    {
        public int Announcement_id { get; set; }
        public string Announcement_headline { get; set; }
        public string Announcement_description { get; set; }
        public string Announcement_image { get; set; }
        public Nullable<bool> Announcement_status { get; set; }
    }
}
