//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Replies
    {
        public int ReplyId { get; set; }
        public Nullable<int> CommentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ReplyText { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    
        public virtual Tbl_Comments Tbl_Comments { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
