//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookingHistory
    {
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int DestinationId { get; set; }
        public int NumberOfAdults { get; set; }
        public int NumberOfChildren { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string CreditCardNumber { get; set; }
        public int PIN { get; set; }
        public int CVV { get; set; }
        public string CardHolderName { get; set; }
        public decimal TotalAmount { get; set; }
        public bool PaymentStatus { get; set; }
        public string BookingStatus { get; set; }
    }
}
