//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Venue()
        {
            this.Tbl_Destination = new HashSet<Tbl_Destination>();
        }
    
        public int Venue_id { get; set; }
        public string Venue_name { get; set; }
        public string Venue_img { get; set; }
        public Nullable<int> Admin_id { get; set; }
        public Nullable<int> Venue_status { get; set; }
    
        public virtual Tbl_Admin Tbl_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Destination> Tbl_Destination { get; set; }
    }
}
