//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Destination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Destination()
        {
            this.Tbl_BookingHistory = new HashSet<Tbl_BookingHistory>();
            this.Tbl_Reviews = new HashSet<Tbl_Reviews>();
            this.Tbl_SavedDestinations = new HashSet<Tbl_SavedDestinations>();
        }
    
        public int DestinationID { get; set; }
        public string DestinationName { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> FK_Venue_Id { get; set; }
        public Nullable<int> US_Id_fk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BookingHistory> Tbl_BookingHistory { get; set; }
        public virtual Tbl_Venue Tbl_Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reviews> Tbl_Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SavedDestinations> Tbl_SavedDestinations { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
