//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Venue
    {
        public int Venue_id { get; set; }
        public string Venue_name { get; set; }
        public string Venue_img { get; set; }
        public Nullable<int> Admin_id { get; set; }
        public Nullable<int> Venue_status { get; set; }
    
        public virtual Tbl_Admin Tbl_Admin { get; set; }
    }
}
