//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreLocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Admin()
        {
            this.Tbl_Venue = new HashSet<Tbl_Venue>();
        }
    
        public int Admin_Id { get; set; }
        public string Admmin_Username { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Venue> Tbl_Venue { get; set; }
    }
}
